FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_APP_URL=http://localhost:3000
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_replace_me
ARG NEXT_PUBLIC_CHECKIN_API_URL=http://localhost:4001
ARG NEXT_PUBLIC_DASHBOARD_API_URL=http://localhost:4002
ARG NEXT_PUBLIC_DOCS_API_URL=http://localhost:4003
ARG NEXT_PUBLIC_SIGNING_API_URL=http://localhost:4004
ARG NEXT_PUBLIC_DEV_AUTH_BYPASS=false
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CHECKIN_API_URL=$NEXT_PUBLIC_CHECKIN_API_URL
ENV NEXT_PUBLIC_DASHBOARD_API_URL=$NEXT_PUBLIC_DASHBOARD_API_URL
ENV NEXT_PUBLIC_DOCS_API_URL=$NEXT_PUBLIC_DOCS_API_URL
ENV NEXT_PUBLIC_SIGNING_API_URL=$NEXT_PUBLIC_SIGNING_API_URL
ENV NEXT_PUBLIC_DEV_AUTH_BYPASS=$NEXT_PUBLIC_DEV_AUTH_BYPASS
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.mjs ./next.config.mjs
EXPOSE 3000
CMD ["npm", "run", "start"]